# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=200)),
                ('Track', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TrackAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimaryTrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Track')),
                ('Users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
