# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('start', '0002_auto_20160417_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputArtist', models.CharField(max_length=200)),
                ('inputSong', models.CharField(max_length=200)),
                ('Track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Track')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
