# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 13, 0, 9, 16496, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
